name: Azure Container scan

on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t helmo_pasi_labo_container
      
    #- uses: Azure/container-scan@v0
    #  with:
    #    image-name: helmo_pasi_labo_container
    
    - uses: Azure/docker-login@v1
      with:
        login-server: helmo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push helmo.azurecr.io/helmo_pasi_labo_container
