name: Azure Container scan

on: [push]

jobs:
  build-secure-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t 'helmo.azurecr.io:${{ github.sha }}'
      
    #- uses: Azure/container-scan@v0
    #  with:
    #    image-name: 'helmo.azurecr.io:${{ github.sha }}'
    
    - uses: Azure/docker-login@v1
      with:
        login-server: helmo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: docker push helmo.azurecr.io/helmo.azurecr.io:${{ github.sha }}
